<a href="https://colab.research.google.com/github/ajaikrishn/Cogno_rise/blob/main/diabetes_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/drive/MyDrive/diabetes_prediction/archive(13).zip')
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [3]:
df['diabetes'].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [4]:
df.isna().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [5]:
df.dtypes

gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
df['gender']=enc.fit_transform(df['gender'])
df['smoking_history']=enc.fit_transform(df['smoking_history'])
df


gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19   
1           0  54.0             0              0                0  27.32   
2           1  28.0             0              0                4  27.32   
3           0  36.0             0              0                1  23.45   
4           1  76.0             1              1                1  20.14   
...       ...   ...           ...            ...              ...    ...   
99995       0  80.0             0              0                0  27.32   
99996       0   2.0             0              0                0  17.37   
99997       1  66.0             0              0                3  27.83   
99998       0  24.0             0              0                4  35.42   
99999       0  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [7]:
df.dtypes

gender                   int64
age                    float64
hypertension             int64
heart_disease            int64
smoking_history          int64
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [8]:
x=df.iloc[:,:-1].values
x

array([[  0.  ,  80.  ,   0.  , ...,  25.19,   6.6 , 140.  ],
       [  0.  ,  54.  ,   0.  , ...,  27.32,   6.6 ,  80.  ],
       [  1.  ,  28.  ,   0.  , ...,  27.32,   5.7 , 158.  ],
       ...,
       [  1.  ,  66.  ,   0.  , ...,  27.83,   5.7 , 155.  ],
       [  0.  ,  24.  ,   0.  , ...,  35.42,   4.  , 100.  ],
       [  0.  ,  57.  ,   0.  , ...,  22.43,   6.6 ,  90.  ]])

In [9]:
y=df.iloc[:,-1]
y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train

array([[  1.  ,  49.  ,   0.  , ...,  27.32,   5.  , 155.  ],
       [  1.  ,  64.  ,   0.  , ...,  27.32,   3.5 , 145.  ],
       [  0.  ,  24.  ,   0.  , ...,  27.32,   3.5 , 130.  ],
       ...,
       [  1.  ,  42.  ,   0.  , ...,  26.14,   5.8 ,  85.  ],
       [  0.  ,  37.  ,   0.  , ...,  24.96,   6.2 , 158.  ],
       [  0.  ,  23.  ,   0.  , ...,  27.99,   5.  , 159.  ]])

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 1.18442308e+00,  3.14317452e-01, -2.86590244e-01, ...,
        -6.19069482e-04, -4.92624842e-01,  4.14557732e-01],
       [ 1.18442308e+00,  9.81097510e-01, -2.86590244e-01, ...,
        -6.19069482e-04, -1.89423192e+00,  1.69109989e-01],
       [-8.42706885e-01, -7.96982644e-01, -2.86590244e-01, ...,
        -6.19069482e-04, -1.89423192e+00, -1.99061626e-01],
       ...,
       [ 1.18442308e+00,  3.15342515e-03, -2.86590244e-01, ...,
        -1.79350769e-01,  2.54898933e-01, -1.30357647e+00],
       [-8.42706885e-01, -2.19106594e-01, -2.86590244e-01, ...,
        -3.58082468e-01,  6.28660821e-01,  4.88192055e-01],
       [-8.42706885e-01, -8.41434648e-01, -2.86590244e-01, ...,
         1.00864183e-01, -4.92624842e-01,  5.12736829e-01]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

knn=KNeighborsClassifier(n_neighbors=7)
r_forest=RandomForestClassifier(n_estimators=100)
d_tree=DecisionTreeClassifier(criterion='entropy')
Linear_regression=LinearRegression()

lst=[knn,r_forest,d_tree]

In [13]:
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print('\n',i,':',accuracy_score(y_test,y_pred))


 KNeighborsClassifier(n_neighbors=7) : 0.9611

 RandomForestClassifier() : 0.9705333333333334

 DecisionTreeClassifier(criterion='entropy') : 0.9547333333333333
